name = "backend"
compatibility_date = "2023-12-01"

[vars]
DATABASE_URL="prisma://accelerate.prisma-data.net/?api_key=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhcGlfa2V5IjoiZTY5OWU2Y2YtMzMxMi00ZGU4LTkyZTgtZDJiNGM5ODRjMDFkIiwidGVuYW50X2lkIjoiYmJhNDM5MmNjMzE4NjI3ZmU5Y2IxMTQ0ZDhhNWIzNDcwYmYwNmY0NmM1NGJkNTE4ODhiOTY3OGY0ZTJiNjYyMiIsImludGVybmFsX3NlY3JldCI6ImJhMzk5NDVjLTQzZjItNDAxOC1hOTYxLWU3ODE2ZDEwODhhMyJ9.0-JwY6zmdp3EY-MYTiKYR64p6ZLWoa1I9e-CgDcJbds"

# [[kv_namespaces]]
# binding = "MY_KV_NAMESPACE"
# id = "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"

# [[r2_buckets]]
# binding = "MY_BUCKET"
# bucket_name = "my-bucket"

# [[d1_databases]]
# binding = "DB"
# database_name = "my-database"
# database_id = ""

# [ai]
# binding = "AI"
